// src/components/Footer.vue
<script setup lang="ts"></script>

<template>
  <footer class="footer">
    <p>made with ❤️ by simone</p>
  </footer>
</template>

<style scoped>
.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  display: flex;
  justify-content: center;
  color: var(--font-color);
  background-color: var(--footer-bg);
}
</style>

// src/components/Footer.svelte
<footer class="section section-footer" style="">
  <div class="docs-footer container grid-lg" id="copyright">
    <p class="text-center">Made with ❤️‍ by Simone</p>
  </div>
</footer>

<style>
  .section-footer {
    background-color: white;
    position: fixed;
    bottom: 0;
    width: 100%;
    height: 2rem;
  }
  @media (max-height: 800px) {
    .section-footer {
      position: static;
    }
  }
</style>
